import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'

const SSXExample = dynamic(
  () => import('../components/SSXExample'),
  { ssr: false }
);

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create SSX Next Dapp</title>
        <meta name="description" content="Generated by create ssx next dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SSXExample />
    </>
  )
}

export default Home;
